microservice:
    payment-service:
        endpoints:
            endpoint:
                uri: http://payment-services/payment/doPayment
    order-service:
        endpoints:
            endpoint:
                uri: http://ORDER-SERVICE/order/bookOrder
